### ISSUE TITLE
Copying assets do not work when a folder has a space in the name

### ISSUE THREAD

**Issue by jkempff** [trulia/hologram#147]
My following setup

``` yml
# hologram_config.yml
source: ./app/styles/
destination: ./docs
documentation_assets: ./doc_assets
dependencies:
  - ./dist/styles/main.css
  - ./dist/scripts/main.js
index: index
```

only creates an index.html file (build correctly) but _none of the dependencies or files from doc_assets/static_ are being copied.
I used the hologram_example assets for testing. Even the cloned example repo does not build correctly.

The stdout says

``` bash
$ hologram
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
Build completed. (-: 
```

Somehow the `cp` command hologram tries to run is mis typed?

I installed hologram (1.2.0) via `bundler`, my Gemfile looks like this

``` ruby
# Gemfile
source 'https://rubygems.org'
gem 'hologram'
```

Am I missing something?
