### ISSUE TITLE
Documentation is generated even when a SASS condition is not met

### ISSUE THREAD

**Issue by alienlebarge** [trulia/hologram#174]
Is there a way to not generate documentation that sit in an not met condition ?
Here's an example:

``` scss

// Predefine the variables below in order to alter and enable specific features.
$border-width:    1px !default;
$border-style:    solid !default;
$border-color:    #ccc !default;

$enable-border-top:    false !default;
$enable-border-right:  false !default;
$enable-border-bottom: false !default;
$enable-border-left:   false !default;

@if $enable-border-top == true {

   /*doc
   ---
   title: Border top
   name: border-top
   parent: border
   ---

  (I escaped the three quotes of `html_example` by using just two)
  ``html_example
      <div class="bt">Content</div>
  ``
   */
  .bt {
    border-top: {
      width: $border-width;
      style: $border-style;
      color: $border-color;
    }
  }

}
```

The documentation for _Border top_ is generated even if `$enable-border-top` is `false`.

Is there a way to fix that ?
