### ISSUE TITLE
using not UTF-8 Chars doesn't work

### ISSUE THREAD

**Issue by lifeiscontent** [trulia/hologram#223]
its perfectly valid to use something like this as a CSS class.

``` css
.ಠ_ಠ {
  color: blue;
}
```

but the hologram dependencies tool modifies the contents of the files that get copied over from `./build`
