### ISSUE TITLE
Create new categories with .md files

### ISSUE THREAD

**Issue by ryanmclaughlin** [trulia/hologram#255]
Hi there,

I'd like to create new pages (categories) in my style guide with simple markdown or html files. The only way I can think of doing this now is by making SASS files with yaml / and markdown to be parsed.

Edit: [Found this pull-request](https://github.com/trulia/hologram/pull/204) that supposedly implemented something that does this, but it doesn't seem to be picking it up and adding it as a category. Example:

```yaml
---
hologram: true
title: Branding
name: brand
category: Brand
---

This is markdown.

```
Is this possible already?
