### ISSUE TITLE
`ignore_paths` causing error

### ISSUE THREAD

**Issue by halleycarleton** [trulia/hologram#259]
When I try to exclude files using ignore_paths I get this error:
```
(erb):1:in `get_binding': undefined local variable or method `rendered_example' for #<Hologram::TemplateVariables:0x000000011c71d0> (NameError)
```

I have not edited any of the included templates/assets and am not using any custom renderers. When I remove `ignore_paths` from the config it works fine.

Here's my files

## Config
```
source: ./public
ignore_paths:
  - "*.scss"
destination: ./public/styleguide
documentation_assets: ./public/_doc_assets
code_example_templates: ./public/_code_example_templates
index: basics
nav_level: all
exit_on_warnings: false
```

## CSS
*(I replaced the backticks with single quotes because I couldn't figure out how to escape them)*
```css
/*doc
---
title: Buttons
name: button
category: Basics
---

Button styles can be applied to any element. Typically you'll want
to use either a `<button>` or an `<a>` element:

'''html_example
<button class="btn">Click</button> <a
class="btn" href="#">Click</a>
'''

*/
.btn {
  display: inline-block;
  background: #bada55;
  border: 4px solid #383838;
  padding: 1em; }
```
