### ISSUE TITLE
Annoying <p class="styleguide"> generated listing CSS styles commented

### ISSUE THREAD

**Issue by nicoguefveneu** [trulia/hologram#261]
Hello,

I got the following HTML generated in the index.html and the basics.html (above the CSS declarations) :
`<p class="styleguide">[OK Button]: basics.html#OK Button
[Search Input]: basics.html#Search Input</p>`

I have two comments in a LESS file ("OK Button" and "Search Input").

It's pretty annoying, how is it possible to get rid of that ?
It's not displayed in your "hologram example".

Thanks !

**Comment by robertbasden** [comment]
Hi there,

I was also having this issue, it turned out that it was caused by having things like:
```yaml
---
title: Colors
name: 1 colors
category: Basics
---
```
in my front matter (I was using the "1" to force the correct ordering, think I saw that as a suggestion on stack overflow or something).

The fix is just to do:
```yaml
---
title: Colors
name: 1-colors
category: Basics
---
```
